databaseChangeLog:
  - include:
      file: db/changelog/product/create/create-product-table.sql
  - include:
      file: db/changelog/product/create/create-catalog-table.sql
  - include:
      file: db/changelog/product/create/create-attribute-table.sql
  - include:
      file: db/changelog/product/create/create-attribute-catalog-table.sql
  - include:
      file: db/changelog/product/create/create-boolean_value-table.sql
  - include:
      file: db/changelog/product/create/create-double_value-table.sql
  - include:
      file: db/changelog/product/create/create-selectable_value-table.sql
  - include:
      file: db/changelog/product/create/create-products_selectable_values-table.sql
  - include:
      file: db/changelog/product/create/create-files-table.sql
  - include:
      file: db/changelog/product/create/add-foreign-key-products.sql
  - include:
      file: db/changelog/product/create/add-foreign-key-attribute-boolean_value.sql
  - include:
      file: db/changelog/product/create/add-foreign-key-attribute-string_value.sql
  - include:
      file: db/changelog/product/create/add-foreign-key-attribute-double_value.sql
  - include:
      file: db/changelog/product/create/add-foreign-key-attributes_catalogs-attribute.sql
  - include:
      file: db/changelog/product/create/add-foreign-key-attributes_catalogs-catalog.sql
  - include:
      file: db/changelog/product/create/add-foreign-key-product-boolean_value.sql
  - include:
      file: db/changelog/product/create/add-foreign-key-product-double_value.sql
  - include:
      file: db/changelog/product/create/add-foreign-key-product-select_value.sql
  - include:
      file: db/changelog/product/create/add-foreign-key-product-select_value2.sql
  - include:
      file: db/changelog/product/create/add-foreign-key-product-files.sql
  - include:
      file: db/changelog/product/complete/complete-catalog.sql
  - include:
      file: db/changelog/product/complete/complete-product.sql
  - include:
      file: db/changelog/product/complete/complete-attribute.sql
  - include:
      file: db/changelog/product/complete/complete-attribute-catalog.sql
  - include:
      file: db/changelog/product/complete/complete-selectable_values.sql
  - include:
      file: db/changelog/product/complete/complete-products_selectable.sql
  - include:
      file: db/changelog/product/complete/complete-products_double-values.sql