export enum ETypographyVariant {
  TextH1Bold = "Text/H1Bold",
  TextH1Medium = "Text/H1Medium",
  TextH2Medium = "Text/H2Medium",
  TextH3Medium = "Text/H3Medium",
  TextH4Medium = "Text/H4Medium",
  TextH5Medium = "Text/H5Medium",
  TextH5Bold = "Text/H5Bold",
  TextH6Bold = "Text/H6Bold",
  TextB2Bold = "Text/B2Bold",
  TextB3Bold = "Text/B3Bold",
  TextB3Medium = "Text/B3Medium",
  TextB3Regular = "Text/B3Regular",
  TextB4Medium = "Text/B4Medium",
  TextB4Regular = "Text/B4Regular",
}
