export enum ROUTES {
  CART = "/cart",
  CONFIRM_REGISTRATION = "/confirm-registration",
  CONFIRM_RESET_PASSWORD = "/confirm-reset-password",
  HOME = "/",
  LOGIN = "/login",
  MIRRORS = "/mirrors",
  MIRRORS_DEFAULT = "/mirrors/?inStock=В+наличии&ordering=-count_in_stock%2Cprice&page=1",
  ORDER = "/order",
  RECIPIENT = "/recipient",
  REVIEWS = "/reviews",
  SHIPPING = "/shipping",
  REGISTRATION = "/registration",
  THANKS = "/thanks",
}
