INSERT INTO products (name, description, alias, count, price, catalog_id,created_at)
VALUES ('Венецианское зеркало Бернард', 'Венецианское зеркало Бернард, 85*125 см',
        'venetian-mirror-bernard', 15, 43000,1, CURRENT_TIMESTAMP),
       ('Венецианское зеркало Лаура', 'Венецианское зеркало Лаура, 62*92 см',
        'venetian-mirror-laura', 11, 32000, 1, CURRENT_TIMESTAMP),
       ('Венецианское зеркало Николь', 'Венецианское зеркало Николь, 80*110 см',
        'venetian-mirror-nikole', 12, 35000, 1, CURRENT_TIMESTAMP),
       ('Венецианское зеркало Коломбо', 'Венецианское зеркало Коломбо, 76*117 см',
        'venetian-mirror-colombo', 19, 31500, 1, CURRENT_TIMESTAMP),
       ('Декоративное зеркало Галакси', 'Декоративное зеркало Галакси, Ø110 см',
        'venetian-mirror-galaxy', 22, 38500, 1, CURRENT_TIMESTAMP),
       ('Венецианское зеркало Шарм', 'Венецианское зеркало Шарм, Ø82,5 см',
        'venetian-mirror-charm', 33, 33000, 1, CURRENT_TIMESTAMP),
       ('Венецианское зеркало Доменик', 'Венецианское зеркало Доменик, 81*120 см',
        'venetian-mirror-domenico', 45, 42500.90, 1, CURRENT_TIMESTAMP),
       ('Зеркало в полный рост Паскаль', 'Зеркало в полный рост Паскаль, 90*190 см',
        'floor_mirror_pascal', 67, 62500, 1, CURRENT_TIMESTAMP),
       ('Зеркало в полный рост Франко Фло', 'Зеркало в полный рост Франко Фло, 110*200 см',
        'floor_mirror_franco_flo', 78, 12345.90, 1, CURRENT_TIMESTAMP),
       ('Зеркало в полный рост Франко Мид', 'Зеркало в полный рост Франко Мид, 90*190 см',
        'floor_mirror_franco_mid', 134, 58000, 1, CURRENT_TIMESTAMP),
       ('Зеркало в полный рост Лайн0', 'Зеркало в полный рост Лайн, 90*190 см',
        'floor_mirror_line', 40, 58000, 1, CURRENT_TIMESTAMP),
       ('Зеркало в полный рост Паоло Золото', 'Зеркало в полный рост Паоло Золото, 92*200 см',
        'floor_mirror_paolo_gold', 40,64000, 1, CURRENT_TIMESTAMP),
       ('Зеркало в полный рост Паоло Серебро', 'Зеркало в полный рост Паоло Серебро, 92*200 см',
        'floor_mirror_paolo_silver', 40, 64000, 1, CURRENT_TIMESTAMP),
       ('Зеркало в полный рост Кингсли Золото', 'Зеркало в полный рост Кингсли Золото, 90*188 см',
        'floor_mirror_kingsley_gold', 40, 52000, 1, CURRENT_TIMESTAMP),
       ('Зеркало в полный рост Кингсли Серебро', 'Зеркало в полный рост Кингсли Серебро, 90*188 см',
        'floor_mirror_kingsley_silver', 40, 52000, 1, CURRENT_TIMESTAMP),
       ('Зеркало в металлической раме Абстракт', 'Зеркало в металлической раме Абстракт, Ø90 см',
        'mirror_sun_abstract', 40, 29500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце в металлической раме Сплэш', 'Зеркало-солнце в металлической раме Сплэш, Ø71 см',
        'mirror_sun_splash', 40, 30000, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце в металлической раме Рейндропс', 'Зеркало-солнце в металлической раме Рейндропс, Ø105 см',
        'mirror_sun_raindrops', 40, 41000, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце в металлической раме Гелиос', 'Зеркало-солнце в металлической раме Гелиос, Ø86 см',
        'mirror_sun_helios', 40, 41500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце в металлической раме Сириус', 'Зеркало-солнце в металлической раме Сириус, Ø90 см',
        'mirror_sun_sirius', 40, 37500, 1, CURRENT_TIMESTAMP),
       ('Зеркало в металлической раме Секвойя', 'Зеркало в металлической раме Секвойя, Ø101 см',
        'mirror_sun_sequoia', 40, 37000, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце Рэй Золото', 'Зеркало-солнце Рэй Золото, Ø74,5 см',
        'mirror_sun_ray_gold', 40, 22500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце Рэй Серебро', 'Зеркало-солнце Рэй Серебро, Ø74,5 см',
        'mirror_sun_ray_silver', 40, 22500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце Саншайн Золото', 'Зеркало-солнце Саншайн Золото, Ø99 см',
        'mirror_sun_sunshine_gold', 40, 39500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце Саншайн Серебро', 'Зеркало-солнце Саншайн Серебро, Ø99 см',
        'mirror_sun_sunshine_silver', 40, 39500, 1, CURRENT_TIMESTAMP),
       ('Зеркало в раме модерн Нексус Золото', 'Зеркало в раме модерн Нексус Золото, Ø91 см',
        'mirror_sun_nexus_gold', 40, 32000, 1, CURRENT_TIMESTAMP),
       ('Зеркало в раме модерн Нексус Серебро', 'Зеркало в раме модерн Нексус Серебро, Ø91 см',
        'mirror_sun_nexus_silver', 40, 32000, 1, CURRENT_TIMESTAMP),
       ('Зеркало в раме модерн Торнадо Золото', 'Зеркало в раме модерн Торнадо Золото, Ø96 см',
        'mirror_sun_tornado_gold', 40, 30000, 1, CURRENT_TIMESTAMP),
       ('Зеркало в раме модерн Торнадо Серебро', 'Зеркало в раме модерн Торнадо Серебро, Ø96 см',
        'mirror_sun_tornado_silver', 40, 30000, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце Солнце Золото', 'Зеркало-солнце Солнце Золото, Ø85 см',
        'mirror_sun_sol_gold', 40, 29500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце Солнце Серебро', 'Зеркало-солнце Солнце Серебро, Ø85 см',
        'mirror_sun_sol_silver', 40, 29500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце Звезда Золото', 'Зеркало-солнце Звезда Золото, Ø76 см',
        'mirror_sun_star_gold', 40, 19500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце Звезда Серебро', 'Зеркало-солнце Звезда Серебро, Ø76 см',
        'mirror_sun_star_silver', 40, 19500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце Нью Солар Золото', 'Зеркало-солнце Нью Солар Золото, Ø103 см',
        'mirror_sun_new_solar_gold', 40, 31000, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце Нью Солар Серебро', 'Зеркало-солнце Нью Солар Серебро, Ø103 см',
        'mirror_sun_new_solar_silver', 40, 31000, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце в металлической раме Кассиопея', 'Зеркало-солнце в металлической раме Кассиопея, Ø100 см',
        'mirror_sun_cassiopeia', 40, 37500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце в металлической раме Бэнг Брасс', 'Зеркало-солнце в металлической раме Бэнг Брасс, Ø99 см',
        'mirror_sun_bang_brass', 40, 36500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце в металлической раме Бэнг Брасс', 'Зеркало-солнце в металлической раме Бэнг Никель, Ø99 см',
        'mirror_sun_bang_nickel', 40, 36500, 1, CURRENT_TIMESTAMP),
       ('Зеркало в металлической раме Баваро', 'Зеркало в металлической раме Баваро, Ø85 см',
        'mirror_sun_bavaro', 40, 34500, 1, CURRENT_TIMESTAMP),
       ('Зеркало в раме модерн Пеон', 'Зеркало в раме модерн Пеон, Ø102 см',
        'mirror_sun_peon', 0, 27500, 1, CURRENT_TIMESTAMP),
       ('Круглое зеркало в раме Фалкон', 'Круглое зеркало в раме Фалкон, Ø81 см',
        'mirror_sun_falcon', 0, 28500, 1, CURRENT_TIMESTAMP),
       ('Зеркало-солнце Рэй Бронза', 'Зеркало-солнце Рэй Бронза, Ø74,5 см',
        'mirror_sun_ray_bronza', 0, 0, 1, CURRENT_TIMESTAMP),
       ('notebook1', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias1', 22, 17000, 2, CURRENT_TIMESTAMP),
       ('notebook2', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias2', 33, 15000, 2, CURRENT_TIMESTAMP),
       ('notebook3', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias3', 42, 18000, 2, CURRENT_TIMESTAMP),
       ('notebook4', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias4', 52, 19000, 2, CURRENT_TIMESTAMP),
       ('notebook5', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias5', 77, 16000, 2, CURRENT_TIMESTAMP),
       ('notebook6', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias6', 45, 55000, 2, CURRENT_TIMESTAMP),
       ('notebook7', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias7', 36, 75000, 2, CURRENT_TIMESTAMP),
       ('notebook8', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias8', 18, 35000, 2, CURRENT_TIMESTAMP),
       ('notebook9', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias9', 15, 44000, 2, CURRENT_TIMESTAMP),
       ('notebook10', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias10', 14, 47000, 2, CURRENT_TIMESTAMP),
       ('notebook11', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias11', 88, 48000, 2, CURRENT_TIMESTAMP),
       ('notebook12', '15.6 Ноутбук Xiaomi Mi Notebook Pro 15.6', 'notebook_alias12', 77, 49000, 2, CURRENT_TIMESTAMP);